function SpawnRegions()
	return {
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "vehicle_interior", file = "media/maps/vehicle_interior/spawnpoints.lua" },
		{ name = "Hopewell, KY", file = "media/maps/Hopewell, KY/spawnpoints.lua" },
		{ name = "Westoutskirts-shippingCo", file = "media/maps/Westoutskirts-shippingCo/spawnpoints.lua" },
		{ name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "BBL", file = "media/maps/BBL/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "CONRTF", file = "media/maps/CONRTF/spawnpoints.lua" },
		{ name = "Canvasback", file = "media/maps/Canvasback/spawnpoints.lua" },
		{ name = "Cedar Hill", file = "media/maps/Cedar Hill/spawnpoints.lua" },
		{ name = "chernaville", file = "media/maps/chernaville/spawnpoints.lua" },
		{ name = "Chestown", file = "media/maps/Chestown/spawnpoints.lua" },
		{ name = "Chinatown", file = "media/maps/Chinatown/spawnpoints.lua" },
		{ name = "Chinatown_EX", file = "media/maps/Chinatown_EX/spawnpoints.lua" },
		{ name = "CigaroHouse", file = "media/maps/CigaroHouse/spawnpoints.lua" },
		{ name = "C_Madriguera", file = "media/maps/C_Madriguera/spawnpoints.lua" },
		{ name = "CorOTRroad", file = "media/maps/CorOTRroad/spawnpoints.lua" },
		{ name = "Eerie A", file = "media/maps/Eerie A/spawnpoints.lua" },
		{ name = "Eerie B", file = "media/maps/Eerie B/spawnpoints.lua" },
		{ name = "Eerie C", file = "media/maps/Eerie C/spawnpoints.lua" },
		{ name = "Eerie D", file = "media/maps/Eerie D/spawnpoints.lua" },
		{ name = "Eerie Country", file = "media/maps/Eerie Country/spawnpoints.lua" },
		{ name = "Elysium_Island", file = "media/maps/Elysium_Island/spawnpoints.lua" },
		{ name = "ExoticsRestArea", file = "media/maps/ExoticsRestArea/spawnpoints.lua" },
		{ name = "Lone", file = "media/maps/Lone/spawnpoints.lua" },
		{ name = "Fort Boonesborough", file = "media/maps/Fort_Boonesborough/spawnpoints.lua" },
		{ name = "Near Fort Knox", file = "media/maps/Near Fort Knox/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Fort Rock Ridge", file = "media/maps/Fort Rock Ridge/spawnpoints.lua" },
		{ name = "Foxwood", file = "media/maps/Foxwood/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "Greenleaf", file = "media/maps/Greenleaf/spawnpoints.lua" },
		{ name = "Greenport", file = "media/maps/Greenport/spawnpoints.lua" },
		{ name = "Heavens Hill", file = "media/maps/Heavens Hill/spawnpoints.lua" },
		{ name = "Hilltop", file = "media/maps/Hilltop/spawnpoints.lua" },
		{ name = "Homepie", file = "media/maps/Homepie/spawnpoints.lua" },
		{ name = "Irvington Road", file = "media/maps/Irvington Road/spawnpoints.lua" },
		{ name = "Irvington, KY", file = "media/maps/Irvington, KY/spawnpoints.lua" },
		{ name = "Jasperville", file = "media/maps/Jasperville/spawnpoints.lua" },
		{ name = "Kingsmouth", file = "media/maps/Kingsmouth/spawnpoints.lua" },
		{ name = "lvinternationalairport", file = "media/maps/lvinternationalairport/spawnpoints.lua" },
		{ name = "LCV2", file = "media/maps/LCV2/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "Lalafell's Fortress", file = "media/maps/Lalafell's Fortress/spawnpoints.lua" },
		{ name = "Lande Desolate Camping", file = "media/maps/Lande Desolate Camping/spawnpoints.lua" },
		{ name = "Leavenburg", file = "media/maps/Leavenburg/spawnpoints.lua" },
		{ name = "RiversideMapFix", file = "media/maps/RiversideMapFix/spawnpoints.lua" },
		{ name = "leavensburgcoreydonroad", file = "media/maps/leavensburgcoreydonroad/spawnpoints.lua" },
		{ name = "Little Crestwood", file = "media/maps/Little Crestwood/spawnpoints.lua" },
		{ name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua" },
		{ name = "HouseLuisMatrioshka", file = "media/maps/HouseLuisMatrioshka/spawnpoints.lua" },
		{ name = "Louisville Mall Base", file = "media/maps/Louisville Mall Base/spawnpoints.lua" },
		{ name = "Louisville_Quarantine_Zone", file = "media/maps/Louisville_Quarantine_Zone/spawnpoints.lua" },
		{ name = "Louisville_River_Marina", file = "media/maps/Louisville_River_Marina/spawnpoints.lua" },
		{ name = "Louisville_Riverboat", file = "media/maps/Louisville_Riverboat/spawnpoints.lua" },
		{ name = "MREX", file = "media/maps/MREX/spawnpoints.lua" },
		{ name = "Military Fuel Depot", file = "media/maps/Military Fuel Depot/spawnpoints.lua" },
		{ name = "MonmouthCounty", file = "media/maps/MonmouthCounty/spawnpoints.lua" },
		{ name = "MuldraughCheckpoint[H]", file = "media/maps/MuldraughCheckpoint[H]/spawnpoints.lua" },
		{ name = "Muldraugh Fire Department", file = "media/maps/Muldraugh Fire Department/spawnpoints.lua" },
		{ name = "NSCarWorkshop", file = "media/maps/NSCarWorkshop/spawnpoints.lua" },
		{ name = "Nettle Township", file = "media/maps/Nettle Township/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "Northwest Blockade", file = "media/maps/Northwest Blockade/spawnpoints.lua" },
		{ name = "OccupiedLouisvilleKY", file = "media/maps/OccupiedLouisvilleKY/spawnpoints.lua" },
		{ name = "ParkingLot", file = "media/maps/ParkingLot/spawnpoints.lua" },
		{ name = "orchidwood", file = "media/maps/orchidwood/spawnpoints.lua" },
		{ name = "OverlookHotel", file = "media/maps/OverlookHotel/spawnpoints.lua" },
		{ name = "PapaVilleModMap", file = "media/maps/PapaVilleModMap/spawnpoints.lua" },
		{ name = "PortCityKY", file = "media/maps/PortCityKY/spawnpoints.lua" },
		{ name = "Portland", file = "media/maps/Portland/spawnpoints.lua" },
		{ name = "RabbitHashKY", file = "media/maps/RabbitHashKY/spawnpoints.lua" },
		{ name = "researchbase", file = "media/maps/researchbase/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "Reststop Louisville", file = "media/maps/Reststop Louisville/spawnpoints.lua" },
		{ name = "Riverside Fire Department", file = "media/maps/Riverside Fire Department/spawnpoints.lua" },
		{ name = "rosewoodcabins", file = "media/maps/rosewoodcabins/spawnpoints.lua" },
		{ name = "Cryo Compound", file = "media/maps/Cryo Compound/spawnpoints.lua" },
		{ name = "Southwood2.0", file = "media/maps/Southwood2.0/spawnpoints.lua" },
		{ name = "Speck", file = "media/maps/Speck/spawnpoints.lua" },
		{ name = "Springwood", file = "media/maps/Springwood/spawnpoints.lua" },
		{ name = "St Paulo", file = "media/maps/St Paulo/spawnpoints.lua" },
		{ name = "TeraMart", file = "media/maps/TeraMart/spawnpoints.lua" },
		{ name = "TheEyeLake", file = "media/maps/TheEyeLake/spawnpoints.lua" },
		{ name = "The Frigate", file = "media/maps/The Frigate/spawnpoints.lua" },
		{ name = "The Oasis", file = "media/maps/The Oasis/spawnpoints.lua" },
		{ name = "The Yacht", file = "media/maps/The Yacht/spawnpoints.lua" },
		{ name = "The Museum", file = "media/maps/The Museum/spawnpoints.lua" },
		{ name = "Tugaland", file = "media/maps/Tugaland/spawnpoints.lua" },
		{ name = "Utopia", file = "media/maps/Utopia/spawnpoints.lua" },
		{ name = "railroadhouse", file = "media/maps/railroadhouse/spawnpoints.lua" },
		{ name = "Waterlocked Pharmaceutical Factory", file = "media/maps/Waterlocked Pharmaceutical Factory/spawnpoints.lua" },
		{ name = "Wellsburg Lake", file = "media/maps/Wellsburg Lake/spawnpoints.lua" },
		{ name = "WhiteRock", file = "media/maps/WhiteRock/spawnpoints.lua" },
		{ name = "EastTownofRiverside", file = "media/maps/EastTownofRiverside/spawnpoints.lua" },
		{ name = "coryerdon", file = "media/maps/coryerdon/spawnpoints.lua" },
		{ name = "elliotpondec", file = "media/maps/elliotpondec/spawnpoints.lua" },
		{ name = "SecretZ_v4", file = "media/maps/SecretZ_v4/spawnpoints.lua" },
		{ name = "Taylorsville", file = "media/maps/Taylorsville/spawnpoints.lua" },
		{ name = "McCoysBunker", file = "media/maps/McCoysBunker/spawnpoints.lua" },
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
	}
end
